name: EMA Bot Scheduler

on:
  schedule:
    - cron: '*/10 * * * *'  # co 10 minut
  workflow_dispatch:

jobs:
  run-ema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run EMA Bot once
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SYMBOLS:      ${{ secrets.SYMBOLS }}   # opcjonalnie
        run: |
          python volume_bot_once.py

